name: DOOMSaveManager Release

on: [push, pull_request]

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2022
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - uses: actions/checkout@master

      - uses: nuget/setup-nuget@v1

      - run: nuget restore DOOMSaveManager.sln
      
      - name: Build Binary
        shell: cmd
        run: call .\BuildBinary.cmd

      - name: Build Artifact
        shell: cmd
        run: call .\BuildArtifact.cmd

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated Release by GitHub Action CI
          draft: false
          prerelease: true

      - name: Upload Release Asset (Any CPU)
        id: upload-release-asset-any-cpu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./DOOMSaveManager.zip
          asset_name: DOOMSaveManager.zip
          asset_content_type: application/zip